### <a name='0'></a> Import of libraries

In [2]:
import numpy as np

# np.__version__

### <a name='1'></a> Exercise 1
Check if all array elements $ A, B, C $ and $ D $ return the logical value _True_.

```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])
```

__Tip:__ Use the function _np.all()_.

In [8]:
# enter solution here
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])

# Axis 0 --> column wise
# Axis 1 --> row wise

print("Array A :\n",A)
print("Axis None : ",np.all(A))
print("Axis 0 : ",np.all(A,axis=0))
print("Axis 1 : ",np.all(A,axis=1))
print("****"*10)
print("Array B :\n",B)
print("Axis None : ",np.all(B))
print("Axis 0 : ",np.all(B,axis=0))
print("Axis 1 : ",np.all(B,axis=1))
print("****"*10)
print("Array C :\n",C)
print("Axis None : ",np.all(C))
print("Axis 0 : ",np.all(C,axis=0))
print("Axis 1 : ",np.all(C,axis=1))
print("****"*10)
print("Array D :\n",D)
print("Axis None : ",np.all(D))
print("Axis 0 : ",np.all(D,axis=0))
# print("Axis 1 : ",np.all(D,axis=1)) --- This is not possible as we have it as 1D array

Array A :
 [[3 2 1 4]
 [5 2 1 6]]
Axis None :  True
Axis 0 :  [ True  True  True  True]
Axis 1 :  [ True  True]
****************************************
Array B :
 [[3 2 1 4]
 [5 2 0 6]]
Axis None :  False
Axis 0 :  [ True  True False  True]
Axis 1 :  [ True False]
****************************************
Array C :
 [[ True False False]
 [ True  True  True]]
Axis None :  False
Axis 0 :  [ True False False]
Axis 1 :  [False  True]
****************************************
Array D :
 [0.1 0.3]
Axis None :  True
Axis 0 :  True


### <a name='2'></a> Exercise 2
Check if all array elements $ A, B $ and $ C $ return the logical value _True_ along the axis with index 1.

```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])
```

__Tip:__ Use the function _np.all()_ with the parameter _axis_.

In [ ]:
# enter solution here
# The solution is provided as part of Exercise 1

### <a name='3'></a> Exercise 3
Check if any element of arrays $ A, B, C $ and $ D $ returns the logical value _True_.

```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```

__Tip:__ Use the _np.any()_ function.

In [9]:
# enter solution here
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

print("Array A :\n",A)
print("Axis None : ",np.any(A))
print("Axis 0 : ",np.any(A,axis=0))
print("Axis 1 : ",np.any(A,axis=1))
print("****"*10)
print("Array B :\n",B)
print("Axis None : ",np.any(B))
print("Axis 0 : ",np.any(B,axis=0))
print("Axis 1 : ",np.any(B,axis=1))
print("****"*10)
print("Array C :\n",C)
print("Axis None : ",np.any(C))
print("Axis 0 : ",np.any(C,axis=0))
print("Axis 1 : ",np.any(C,axis=1))
print("****"*10)
print("Array D :\n",D)
print("Axis None : ",np.any(D))
print("Axis 0 : ",np.any(D,axis=0))
# print("Axis 1 : ",np.any(D,axis=1)) --- This is not possible as we have it as 1D array

Array A :
 [[0 0 0]
 [0 0 0]]
Axis None :  False
Axis 0 :  [False False False]
Axis 1 :  [False False]
****************************************
Array B :
 [[0 0 0]
 [0 1 0]]
Axis None :  True
Axis 0 :  [False  True False]
Axis 1 :  [False  True]
****************************************
Array C :
 [[False False False]
 [ True False False]]
Axis None :  True
Axis 0 :  [ True False False]
Axis 1 :  [False  True]
****************************************
Array D :
 [[0.1 0. ]]
Axis None :  True
Axis 0 :  [ True False]


### <a name='4'></a> Exercise 4
Check if any element of arrays $ A, B, C $ and $ D $ returns the logical value _True_ along the axis with index 0.

```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```

__Tip:__ Use the _np.any()_ function with the parameter _axis_.


In [ ]:
# enter solution here
# The solution is provided as part of Exercise 3

### <a name='5'></a> Exercise 5
Check the array $ A $ for missing data (_np.nan_).

```
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
```
__Tip:__ Use the _np.isnan()_ function.


In [11]:
# enter solution here
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])

print("Array A :\n",A)
print("Axis None : \n",np.isnan(A,axi))

Array A :
 [[ 3.  2.  1. nan]
 [ 5. nan  1.  6.]]
Axis None : 
 [[False False False  True]
 [False  True False False]]


### <a name='6'></a> Exercise 6
Check if the following arrays $ A $ and $ B $ are equal in terms of elements (element-wise) with the specified tolerance level. Use the _np.allclose()_ function with default parameters.

```
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])
```

In [25]:
# enter solution here
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

np.allclose(A,B)
# np.allclose compares individual elements of two array with same dimension. Its used to check if the float values are
# approximately equal to each other

True

### <a name='7'></a> Exercise 7
Check if the following arrays $ A $ and $ B $ are equal in terms of elements (element-wise). Use the comparison operator _==_.

```
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])
```

In [38]:
# enter solution here
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])

print(A==B)
# This gives us True if each element exactly matches

# Other possibilities
# A = np.array([0.4, 0.5, 0.3,None])
# B = np.array([0.3999999999, 0.5000000001, 0.3,None])

# A = np.array([0.4, 0.5, 0.3])
# B = np.array([0.3999999999, 0.5000000001, 0.3,None])

# A = np.array([1,1,1])
# B = np.array([1,1,1,1])

# A==B
# If the number of elements dont match it does overall comparision

[False False  True]


C:\Users\theve\AppData\Local\Temp\ipykernel_9976\1862348711.py:18: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  A==B


False

### <a name='8'></a> Exercise 8

Check which elements (element-wise) from the array $ A $ below have higher values than the array $ B $.

```
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])
```

In [40]:
# enter solution here
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

A>B

array([ True, False,  True, False])

### <a name='9'></a> Exercise 9

Create an array of numpy dimensions _4x4_ filled with zeros. Set the data type to _int_.

__Expected result:__

```
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])
```
__Tip:__ Use the _np.zeros()_ function.

In [47]:
# enter solution here
# help(np.zeros)
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### <a name='10'></a> Exercise 10
Create an array of numpy dimensions _10x10_ filled with number 255. Set the data type to _float_.

__Expected result:__
```
array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])
```

__Tip:__ Use the _np.ones()_ or _np.full()_ functions.

In [54]:
# enter solution here
# help(np.full)
np.ones((10,10),dtype=float)*255
np.full((10,10),255,dtype=float)

array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])

### <a name='1'></a> Exercise 11
Build a one-dimensional numpy array of two-digit numbers.

__Expected result:__
```
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])
```

__Tip:__ Use the _np.arange()_ function.


In [55]:
# enter solution here
np.arange(10,100,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

### <a name='2'></a> Exercise 12

Build the numpy array specified below:

```
array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
```

Note that the shape of the array is (9, 10).

__Tip:__ Use the _np.arange()_ function and the _np.ndarray.reshape()_ method.



In [57]:
# enter solution here
arr1 = np.arange(10,100,1)
print("Array 1 :\n",arr1)
np.reshape(arr1,(9,10))

Array 1 :
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### Reminder

### Identity matrix:

Identity matrix - a square matrix which coefficients are given by the formula:
$${\displaystyle a_{ij}={\begin{cases}1\quad {\text{dla}}\quad i=j\\[2pt]0\quad {\text{dla}}\quad i\neq j\end{cases}}}$$

#### Examples:
${\displaystyle I_{1}={\begin{bmatrix}1\end{bmatrix}},\;I_{2}={\begin{bmatrix}1&0\\0&1\end{bmatrix}},\;I_{3}={\begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix}}}$

### <a name='3'></a> Exercise 13

Build a _6x6_ two-dimensional array - identity matrix. Use the _int_ data type.

__Expected result:__

```
array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])
```
__Tip:__ Use the _np.eye()_ function.


In [58]:
# enter solution here
np.eye(6,6,dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

### <a name='4'></a> Exercise 14

Set the random seed to 10. Then build a one-dimensional array consisting of 30 pseudo-randomly generated values from the uniform distribution above the $ [0, 1) $ interval.

__Expected result:__

```
array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578,
       0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317,
       0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895])
```
__Tip:__ Use the function _np.random.rand()_.


In [60]:
# enter solution here
np.random.rand(30)

array([0.00461576, 0.72799598, 0.23866819, 0.3633544 , 0.82572008,
       0.14550031, 0.71010322, 0.18341919, 0.27768263, 0.818305  ,
       0.05866269, 0.61187634, 0.41630076, 0.75450275, 0.83419752,
       0.36803782, 0.44617947, 0.09860683, 0.52850612, 0.1322726 ,
       0.50172906, 0.66362071, 0.22281019, 0.78119052, 0.73621713,
       0.32831076, 0.08697485, 0.33806828, 0.97469048, 0.32593037])

### <a name='5'></a> Exercise 15

Set the random seed to 20. Then build a two-dimensional array with the shape _(10, 4)_ pseudo-random values generated from the standard normal distribution $ N (0, 1) $.

__Expected result:__
```
array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191],
       [-1.08483259,  0.55969629,  0.93946935, -0.97848104],
       [ 0.50309684,  0.40641447,  0.32346101, -0.49341088],
       [-0.79201679, -0.84236793, -1.27950266,  0.24571517],
       [-0.0441948 ,  1.56763255,  1.05110868,  0.40636843],
       [-0.1686461 , -3.18970279,  1.12013226,  1.33277821],
       [-0.24333877, -0.13003071, -0.10901737,  1.55618644],
       [ 0.12877835, -2.06694872, -0.88549315, -1.10457948],
       [ 0.93286635,  2.059838  , -0.93493796, -1.61299022],
       [ 0.52706972, -1.55110074,  0.32961334, -1.13652654]])
```
__Tip:__ Use the function _np.random.randn()_.


In [71]:
# enter solution here
np.random.seed(20)
np.random.randn(10,4)
# help(np.random.randn)

array([[ 0.72412728, -0.18015931,  0.15257919,  1.22994294],
       [ 0.27207689,  0.07507401,  0.08681927, -2.51535428],
       [ 1.85004388, -0.17580646,  0.903463  , -1.54515935],
       [ 1.4414779 ,  0.26883223,  0.42905404,  0.4363884 ],
       [-0.4382602 ,  1.42049845,  1.9554321 , -0.39157542],
       [ 0.12072221,  0.4140251 ,  1.36650573, -1.36321998],
       [ 0.01565366,  0.90466021, -0.80690109, -0.70631035],
       [ 1.05289192, -0.09347129, -1.43895054, -0.31126891],
       [ 0.80566924, -0.01255094, -0.26082291, -0.88947773],
       [-1.61589921, -0.8519646 , -0.04118014, -0.2703269 ]])

### <a name='6'></a> Exercise 16
Set the random seed to 30. Then build a two-dimensional array with the shape _(10, 4)_ pseudo-random values generated from the normal distribution $ N (100, 5) $.
$\mu=100$   
$\sigma^{2}=5$

__Expected result:__
```
array([[ 97.17349231, 103.41650023,  97.82942436, 101.05220329],
       [ 99.7748353 , 100.67930221,  96.14063068, 103.544381  ],
       [100.30029631,  97.52499594, 103.52901961, 100.24037271],
       [ 98.29153712,  98.2666258 , 103.09437633, 101.70027274],
       [ 99.36127721, 101.20382627,  95.34026547, 102.09694365],
       [ 99.98708001,  98.95468525,  99.05410904, 102.38025432],
       [ 93.50787269, 103.61547679, 103.18753701,  98.51356237],
       [102.20256689,  96.19764407,  97.54000366,  97.05813038],
       [101.81233513,  97.66380453,  98.45883627,  98.09317768],
       [102.48979932,  95.70413391,  98.43161651, 101.89861815]])
```
__Tip:__ Use the function _np.random.rand()_.


In [91]:
# enter solution here
np.random.seed(30)
mean = 100
std = np.sqrt(5)
mean+std*np.random.randn(10,4)
# Normal deviation - formula used - Statistics
# Check

array([[ 97.17349231, 103.41650023,  97.82942436, 101.05220329],
       [ 99.7748353 , 100.67930221,  96.14063068, 103.544381  ],
       [100.30029631,  97.52499594, 103.52901961, 100.24037271],
       [ 98.29153712,  98.2666258 , 103.09437633, 101.70027274],
       [ 99.36127721, 101.20382627,  95.34026547, 102.09694365],
       [ 99.98708001,  98.95468525,  99.05410904, 102.38025432],
       [ 93.50787269, 103.61547679, 103.18753701,  98.51356237],
       [102.20256689,  96.19764407,  97.54000366,  97.05813038],
       [101.81233513,  97.66380453,  98.45883627,  98.09317768],
       [102.48979932,  95.70413391,  98.43161651, 101.89861815]])

### <a name='7'></a> Exercise 17
Iterating by array numpy $ A $ element by element (element-wise) print each element of the array to the console.

```
A = np.array([[1, 4, 3],
              [5, 2, 6]])
```

__Tip:__ Use the _np.nditer()_ function.


In [95]:
# enter solution here
A = np.array([[1, 4, 3],
              [5, 2, 6]])
# help(np.nditer)
for element in np.nditer(A):
    print(element)
    
# nditer is used to iterate the array based on the elements present

1
4
3
5
2
6


### <a name='8'></a> Exercise 18
Create a one-dimensional numpy array (vector) consisting of 11 equally spaced points from the interval $ [0, 1]. $

__Expected result:__
```
array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])
```
__Tip:__ Use the _np.linspace()_ function.



In [96]:
# enter solution here
np.linspace(0,1,num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### <a name='9'></a> Exercise 19

Set the random seed to 42. Generate a one-dimensional array (vector) containing the possible result from the Big Lotto game.

__Expected result:__
```
array([39, 29, 15, 43,  8, 21])
```

__Tip:__ The result of the game is a 6-element vector of values from 1 to 49 inclusive.



In [121]:
# enter solution here
np.random.seed(42)
np.random.choice(np.arange(1, 50), size=6)

array([39, 29, 15, 43,  8, 21])

### <a name='10'></a> Exercise 20
Build the two-dimensional _6x6_ size array below:

```
array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])
```
__Tip:__ Use the _np.diag()_ function.



In [132]:
# enter solution here
a1 = [0,1,2,3,4,5]
# a1 = np.array([0,1,2,3,4,5])
a1
np.diag(a1,k=0)

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

### <a name='1'></a> Exercise 21
Generate the following numpy array. Save the array to a binary file named _'array.npy'_ and then load that file back into another variable.

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```
__Tip:__ Use the _np.save()_ and _np.load()_ functions.


In [133]:
# enter solution here
a1 = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
a1
np.save('array.npy',a1)
np.load('array.npy')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### <a name='2'></a> Exercise 22
Generate the following numpy array:
```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```

Save the array to a text file named _'array.txt'_ with two decimal places and then load the file back into another variable.

__Tip:__ Use the _np.savetxt()_ and _np.loadtxt()_ functions.


In [136]:
# enter solution here
a1 = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
a1
np.savetxt('array.txt',a1)
np.loadtxt('array.txt')

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

### <a name='3'></a> Exercise 23
Generate and convert the following numpy array into a list:

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```
__Tip:__ Use the _np.array.tolist()_ method.


In [142]:
# enter solution here
a1 = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
l1 = a1.tolist()
type(l1)

list

### <a name='4'></a> Exercise 24
The following numpy array is given:
```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```

Using the cut operator, transform the array into the following:

* swap rows (first with last)

```
array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])
```

In [151]:
# enter solution here
a1 = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
a1[::-1]

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

* swap columns (reverse order)

```
array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])
```

In [153]:
# enter solution here
a1 = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
a1[::,::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

* swapp rows and columns (reverse order)

```
array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])
```

In [154]:
# enter solution here
a1 = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
a1[::-1,::-1]

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

### <a name='5'></a> Exercise 25
The following numpy array:

```
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
```
Transform to array:

```
array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])
```

__Tip:__ Use the _np.pad()_ function.

In [163]:
# enter solution here
a1 = [[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]]
a1
# help(np.pad)
np.pad(a1,pad_width=1,mode='constant',constant_values=0)

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

### <a name='6'></a> Exercise 26
The following numpy array:
```
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])
```

Transform to array:
```
array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])
```

__Tip:__ Use the cut operator and assign the appropriate values.


In [180]:
# enter solution here
a1 = np.zeros((6,6),dtype=int)
a1[::2,::2]=10
a1[1::2,::2]=5
a1

array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])

### <a name='7'></a> Exercise 27
Combine the following arrays: $ A $ and $ B $ into one array.

```
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
```

__The expected result:__

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])
```

__Tip:__ Use the _np.append()_ function.


In [182]:
# enter solution here
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
# help(np.append)
np.append(A,B,axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])

### <a name='8'></a> Exercise 28
Use the $ A $ and $ B $ arrays below to extract the common elements (intersection) of the arrays.

```
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])      
```
__Tip:__ Use the _np.intersect1d()_ function.

In [185]:
# enter solution here
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])
# help(np.intersect1d)
print(A)
print(B)
np.intersect1d(A,B)

[[0 1 2 3]
 [4 5 6 7]]
[[ 9 10 11  3]
 [ 2  8  0  9]]


array([0, 2, 3])

### <a name='9'></a> Exercise 29
The following numpy array $ A $ is given.
Find the unique values of this array.

```
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])
```

__Tip:__ Use the _np.unique()_ function.

In [186]:
# enter solution here
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])
np.unique(A)

array([1, 2, 4, 5, 7, 9])

### <a name='10'></a> Exercise 30
The array below is given:
```
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
```
Return indexes with maximum values for a given row.

__Tip:__ Use the _np.argmax()_ function.

In [190]:
# enter solution here
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
np.argmax(A,axis=1)

array([0, 2, 1], dtype=int64)

### <a name='1'></a> Exercise 31
Sort the array $ A $ below:
* by row (ascending)
* by column (ascending)

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```
__Tip:__ Use the _np.sort()_ function.


In [194]:
# enter solution here
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
A
print("Column : \n",np.sort(A,axis=0))
print("Row : \n",np.sort(A,axis=1))

Column : 
 [[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]
Row : 
 [[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]


### <a name='2'></a> Exercise 32
Extract all elements of the $ A $ array with a value greater than 8.
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```

In [199]:
# enter solution here
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
B = A[A>8]
print(type(B))
print(B)

<class 'numpy.ndarray'>
[ 9.99  9.99 14.99]


### <a name='3'></a> Exercise 33
The following array $ A $ is given. Replace elements above 10 with a fixed value of 10 (truncation to 10).

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Tip:__ Use the _np.where()_ function.


In [204]:
# enter solution here
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
# help(np.where)
np.where(A>10,10,A)

array([[ 4.99,  3.49,  9.99],
       [ 1.99,  9.99, 10.  ],
       [10.  ,  2.39,  7.29]])

### <a name='4'></a> Exercise 34
Present the following $ A $ two-dimensional array as a "flattened" one-dimensional array.
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Expected result:__
```
array([ 4.99,  3.49,  9.99,  1.99,  9.99, 14.99, 14.99,  2.39,  7.29])
```

__Tip:__ Use the _np.ravel()_ function.

In [207]:
# enter solution here
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
np.ravel(A)
# help(np.ravel)

array([ 4.99,  3.49,  9.99,  1.99,  9.99, 14.99, 14.99,  2.39,  7.29])

### <a name='5'></a> Exercise 35
Build an array of the same shape and data type as the $ A $ array and fill it with a constant value of 0.0.

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Expected result:__
```
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
```

__Tip:__ Use the _np.zeros_like()_ function.

In [214]:
# enter solution here
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
# np.where(A,0.,0.)
np.zeros_like(A)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### <a name='6'></a> Exercise 36

Build an array of the same shape and data type as the $ A $ array and fill it with a constant value of 9.99.

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Expected result:__

```
array([[9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99]])
```

__Tip:__ Use the function _np.full_like()_.




In [215]:
# enter solution here
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
np.full_like(A,9.99)

array([[9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99]])

### <a name='7'></a> Exercise 37
Build a two-dimensional array (lower triangular matrix) below:
```
array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])
```
__Tip:__ Use the _np.tri()_ function.

In [219]:
# enter solution here
# help(np.tri)
np.tri(5,5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

### <a name='8'></a> Exercise 38
Create any $ (2, 3, 4) $ 3-dimensional array.

In [220]:
# enter solution here
np.random.random((2,3,4))

array([[[0.15601864, 0.15599452, 0.05808361, 0.86617615],
        [0.60111501, 0.70807258, 0.02058449, 0.96990985],
        [0.83244264, 0.21233911, 0.18182497, 0.18340451]],

       [[0.30424224, 0.52475643, 0.43194502, 0.29122914],
        [0.61185289, 0.13949386, 0.29214465, 0.36636184],
        [0.45606998, 0.78517596, 0.19967378, 0.51423444]]])

### <a name='9'></a> Exercise 39
Generate a two-dimensional array _(200, 300)_ filled with random values from 0 to 255 (inclusive) with data type _np.uint8_ and assign to the variable _image_.

In [226]:
# enter solution here
np.random.randint(0,256,size=(200,300),dtype=np.uint8)

array([[211,  62, 187, ...,  62, 209,   9],
       [ 69,  70, 117, ..., 213, 148,  19],
       [112, 241, 214, ...,  39,  80, 141],
       ...,
       [ 27, 249, 141, ..., 216, 231,  47],
       [165,  54,  72, ...,  31, 238, 198],
       [ 18, 101,  55, ...,  90, 131,  70]], dtype=uint8)

Then run the following block of code. As a result, you'll get a preview of the randomly generated black and white image.

In [232]:
image = np.random.randint(0,256,size=(200,300),dtype=np.uint8)
# from google.colab.patches import cv2_imshow

# cv2_imshow(image)
image

array([[ 21, 105, 177, ..., 177,  70, 215],
       [  3,  45,  35, ..., 166, 219, 188],
       [194, 167, 126, ..., 216,  20, 200],
       ...,
       [ 62, 168, 120, ..., 172,  15,  57],
       [ 70,  47, 230, ..., 116,  96, 217],
       [210,   0, 203, ..., 165, 187, 207]], dtype=uint8)

### <a name='10'></a> Exercise 40
Sort the array _image_ from the previous exercise along the row in ascending order. Then display the image with the _cv2_imshow()_ function.

In [246]:
# enter solution here
image_2 = np.sort(image,axis=1)
# from google.colab.patches import cv2_imshow

# cv2_imshow(image_2)
image_2

array([[  0,   1,   2, ..., 253, 255, 255],
       [  0,   0,   2, ..., 254, 254, 254],
       [  0,   4,   5, ..., 253, 254, 254],
       ...,
       [  1,   3,   3, ..., 252, 253, 255],
       [  0,   1,   1, ..., 254, 255, 255],
       [  0,   1,   1, ..., 251, 253, 255]], dtype=uint8)

Sort the array _image_ from the previous exercise along the column in ascending order. Then display the image with the _cv2_imshow()_ function.

In [247]:
# enter solution here
image_3 = np.sort(image,axis=0)
# from google.colab.patches import cv2_imshow

# cv2_imshow(image_3)
image_3

array([[  0,   0,   1, ...,   0,   0,   0],
       [  0,   0,   3, ...,   5,   1,   2],
       [  2,   4,   3, ...,   6,   1,   6],
       ...,
       [249, 253, 250, ..., 253, 255, 249],
       [252, 254, 251, ..., 253, 255, 250],
       [255, 254, 252, ..., 254, 255, 255]], dtype=uint8)

In [245]:
A=np.array([[1,8,3]
            ,[3,4,1]])
print(A)
# print(np.sort(A))
print(np.sort(A,axis=0))
print(np.sort(A,axis=1))
print("*******"*10)
print(np.sum(A,axis=0))
print(np.sum(A,axis=1))

[[1 8 3]
 [3 4 1]]
[[1 4 1]
 [3 8 3]]
[[1 3 8]
 [1 3 4]]
**********************************************************************
[ 4 12  4]
[12  8]


### <a name='1'></a> Exercise 41
The following array $ A $ with the shape (2, 3) is given.
```
A = np.array([[4, 2, 1],
              [6, 4, 2]])
```

In [248]:
# enter solution here
A = np.array([[4, 2, 1],
              [6, 4, 2]])

* Expand the array $ A $ by one dimension (add a new dimension at the beginning). Expected shape of the output array: _(1, 2, 3)_.

__Tip:__ Use the _np.expand_dims()_ function.

In [252]:
# enter solution here
# help(np.expand_dims)
B = np.expand_dims(A,axis=0)
print(A.shape)
print(B.shape)
B

(2, 3)
(1, 2, 3)


array([[[4, 2, 1],
        [6, 4, 2]]])

* Expand the array $ A $ by one dimension (add a new dimension at the end). Expected shape of the output array: _(2, 3, 1)_.

__Tip:__ Use the _np.expand_dims()_ function.

In [254]:
# enter solution here
C = np.expand_dims(A,axis=2)
print(A.shape)
print(C.shape)
C

(2, 3)
(2, 3, 1)


array([[[4],
        [2],
        [1]],

       [[6],
        [4],
        [2]]])

### <a name='2'></a> Exercise 42
Generate a three-dimensional array named _image_ with shape _(200, 300, 3)_ filled with random values from 0 to 255 inclusive and data type _np.uint8_.

In [255]:
# enter solution here
np.random.randint(0,256,size=(200,300,3),dtype=np.uint8)

array([[[138,  10, 216],
        [  2, 163, 215],
        [252, 228, 227],
        ...,
        [ 14,  67, 161],
        [120,  90, 173],
        [207, 211,  60]],

       [[ 71, 215,  65],
        [238, 220, 175],
        [ 27, 150, 118],
        ...,
        [228, 104,  92],
        [ 53, 141, 112],
        [  1, 122,  19]],

       [[ 50, 126, 205],
        [149, 171, 160],
        [ 30, 105,  69],
        ...,
        [ 90,   8,  95],
        [ 77,  40,  24],
        [231, 195,  33]],

       ...,

       [[182, 187,  11],
        [  2, 119, 159],
        [135, 135,  49],
        ...,
        [229,  76,  27],
        [182, 198,  27],
        [ 33, 109,   6]],

       [[ 23, 233, 134],
        [ 30, 253,  90],
        [ 61,   3,  21],
        ...,
        [151, 207, 160],
        [ 80, 141,  96],
        [152,  52, 206]],

       [[233, 255, 245],
        [130,  88, 243],
        [138, 213, 242],
        ...,
        [191, 185,   8],
        [ 61, 110,  82],
        [ 34,  77, 181]]

Then run the following block of code. As a result, you'll get a preview of a randomly generated color image.

In [262]:
image = np.random.randint(0,256,size=(200,300,3),dtype=np.uint8)
# from google.colab.patches import cv2_imshow

# cv2_imshow(image)
image.shape

(200, 300, 3)

__Note:__ The color image can be saved as a three-dimensional numpy array with the shape: (height, width, channel).

### <a name='3'></a> Exercise 43
The _image_ array from the previous task is of the shape _(200, 300, 3)_. Follow the instructions:
* Extend the _image_ array by one dimension (add a new dimension at the beginning). Expected shape of the output array: _(1, 200, 300, 3)_.

__Tip:__ Use the _np.expand_dims()_ function.

In [263]:
# enter solution here
image_1 = np.expand_dims(image,axis=0)
print(image.shape)
print(image_1.shape)
image_1

(200, 300, 3)
(1, 200, 300, 3)


array([[[[ 30, 216, 188],
         [159,  90, 134],
         [ 17, 200, 117],
         ...,
         [ 41, 213, 112],
         [201, 130, 144],
         [ 81,  27, 151]],

        [[120, 201,  88],
         [ 53, 235,  11],
         [232, 118, 250],
         ...,
         [241,  57, 137],
         [216, 202,  99],
         [ 51, 138,  76]],

        [[140, 208,  21],
         [156, 253,  32],
         [225,  76,  36],
         ...,
         [ 60,  21,   8],
         [110, 159, 183],
         [  7,  22, 223]],

        ...,

        [[ 14, 237, 224],
         [191,  34, 164],
         [  3,  39,  29],
         ...,
         [ 43,  63, 151],
         [ 68,  74, 128],
         [ 67,  60,   0]],

        [[201, 149, 132],
         [ 52,  77, 147],
         [201, 229, 177],
         ...,
         [195,  30,  70],
         [111, 206, 165],
         [222,  74, 168]],

        [[222,  47, 146],
         [ 53, 152,  97],
         [120, 246, 229],
         ...,
         [182,  95, 239],
        

In [260]:
# Creating a sample array to represent the image
image = np.random.randint(0, 256, size=(200, 300, 3), dtype=np.uint8)

# Add a new dimension at the beginning of the array
expanded_image = np.expand_dims(image, axis=0)

print("Original shape:", image.shape)
print("Expanded shape:", expanded_image.shape)

Original shape: (200, 300, 3)
Expanded shape: (1, 200, 300, 3)


* Extend the _image_ array by one dimension (add a new dimension at the end). Expected shape of the output array: _(200, 300, 3, 1)_.

__Tip:__ Use the _np.expand_dims()_ function.

In [266]:
# enter solution here
image_2 = np.expand_dims(image,axis=3)
print(image.shape)
print(image_2.shape)
image_2

(200, 300, 3)
(200, 300, 3, 1)


array([[[[ 30],
         [216],
         [188]],

        [[159],
         [ 90],
         [134]],

        [[ 17],
         [200],
         [117]],

        ...,

        [[ 41],
         [213],
         [112]],

        [[201],
         [130],
         [144]],

        [[ 81],
         [ 27],
         [151]]],


       [[[120],
         [201],
         [ 88]],

        [[ 53],
         [235],
         [ 11]],

        [[232],
         [118],
         [250]],

        ...,

        [[241],
         [ 57],
         [137]],

        [[216],
         [202],
         [ 99]],

        [[ 51],
         [138],
         [ 76]]],


       [[[140],
         [208],
         [ 21]],

        [[156],
         [253],
         [ 32]],

        [[225],
         [ 76],
         [ 36]],

        ...,

        [[ 60],
         [ 21],
         [  8]],

        [[110],
         [159],
         [183]],

        [[  7],
         [ 22],
         [223]]],


       ...,


       [[[ 14],
         [237],
      

### <a name='4'></a> Exercise 44
Two randomly generated arrays _image1_ and _image2_ are given.

```
image1 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
image2 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
```

Expand each of these arrays by adding one dimension at the beginning and then combine the arrays into one called _images_. Expected shape of array: _(2, 200, 300, 3)_.



In [275]:
image1 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
image2 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)

# enter solution here
image3 = np.expand_dims(image1,axis=0)
image4 = np.expand_dims(image2,axis=0)
image5 = np.concatenate((image3,image4),axis=0)
print(image1.shape)
print(image2.shape)
print(image3.shape)
print(image4.shape)
print(image5.shape)
# Check

(200, 300, 3)
(200, 300, 3)
(1, 200, 300, 3)
(1, 200, 300, 3)
(2, 200, 300, 3)


### <a name='5'></a> Exercise 45
From the _images_ array from the previous exercise, extract the first ten rows and the first ten columns from the third channel (index 2) for the first picture.

In [285]:
# enter solution here
first_pic = image5[0]
first_pic[:10,:10,2]

array([[162,  83, 167, 216, 253,  25,  85, 200,  56,  94],
       [ 72,   4, 131, 110,  36, 242,  51, 185, 117,  63],
       [156, 110,  25,  73, 119,  48, 175,  11,  76,  33],
       [240,  66,  47, 254, 124, 111, 189,  64, 144,  17],
       [201,  32,   7, 233, 148,  18, 164, 227, 158, 138],
       [152,  24, 118, 245, 177, 135, 196, 187,  49, 237],
       [141, 103,  32, 124, 223,  39,  24, 114, 217,  89],
       [148,  36, 221, 158, 167, 171,   5, 133, 158, 110],
       [118, 131, 174, 225, 161,  30, 246,  38, 122,   1],
       [ 33, 132,  58,  34,  91,  96, 249,  63, 207,  20]], dtype=uint8)

### <a name='6'></a> Exercise 46
From the _images_ array extract the first hundred rows and the first hundred columns for the second image from the first channel (index 0) and display using the function _cv2_imshow_.

In [ ]:
# enter solution here
# Check

### <a name='7'></a> Exercise 47
Below is a preview of the first image from the array _images_ from Exercise 44.



In [ ]:
cv2_imshow(images[0])
# Check

For the first image from the array _images_, assign for pixels with the index $ [50: 150, 100: 200] $ the value 0 and then display the image.

In [ ]:
# enter solution here

For the second image from the array _images_, assign for the pixel with the index $ [100: 150, 10:150] $ the value 255 and then display the image.

In [ ]:
# enter solution here

### <a name='8'></a> Exercise 48
The following array $ A $ with the shape _(1, 2, 3)_ is given.

```
A = np.array([[[1, 2, 3],
               [6, 3, 2]]])
```

Remove the unnecessary first dimension and get an array of _(2, 3)_.

__Tip:__ Use the _np.squeeze()_ function.


In [290]:
# enter solution here
A = np.array([[[1, 2, 3],
               [6, 3, 2]]])
print(np.squeeze(A).shape)
np.squeeze(A)

(2, 3)


array([[1, 2, 3],
       [6, 3, 2]])

### <a name='9'></a> Exercise 49
The following array $ A $ with the shape _(4, 1)_ is given.
```
A = np.array([[0.4],
              [0.9],
              [0.5],
              [0.6]])
```
Remove the unnecessary dimension and get an array with the shape _(4,)_.

__Tip:__ Use the _np.squeeze()_ function.

In [291]:
# enter solution here
A = np.array([[0.4],
              [0.9],
              [0.5],
              [0.6]])
print(np.squeeze(A).shape)
np.squeeze(A)

(4,)


array([0.4, 0.9, 0.5, 0.6])

### <a name='10'></a> Exercise 50
The first image was extract from the _images_ array as follows:

In [ ]:
image1 = images[:1]
image1.shape

Using the knowledge from previous exercises, remove the unnecessary first dimension of the _image1_ array.

In [ ]:
# enter solution here
# Check

### <a name='1'></a> Exercise 51
Two arrays $ A $ and $ B $ are given below:

```
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
```
* Concatenate these arrays as follows:

```
array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])
```

__Tip:__ Use the _np.concatenate()_ function.

In [293]:
# enter solution here
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
np.concatenate((A,B),axis=0)

array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])

* Concatenate these arrays as follows:

```
array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])
```
__Tip:__ Use the _np.concatenate()_ function.

In [294]:
# enter solution here
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
np.concatenate((A,B),axis=1)

array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])

### <a name='2'></a> Exercise 52
The first array is given containing the data (_data_) and the second array containing the target class (_target_) for the given row:

```
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
```

Concatenate these arrays into one as shown below:

```
array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])
```

In [296]:
# enter solution here
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
np.concatenate((data,target),axis=1)

array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

### <a name='3'></a> Exercise 53
The following three one-dimensional arrays are given:
```
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
```
Transform each of these arrays into a column and concatenate them into one large array.

__Expected result:__
```
array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])
```
__Tip:__ Use the function _np.column_stack()_.


In [302]:
# enter solution here
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
# feature1.reshape((-1,1))
np.concatenate((feature1.reshape((-1,1)),feature2.reshape((-1,1)),feature3.reshape((-1,1))),axis=1)
np.column_stack((feature1,feature2,feature3))

array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])

### <a name='4'></a> Exercise 54
The following two-dimensional array is given:
```
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A
```
```
array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])
```
Split an array into three parts so that the first two columns formed the first array $ A1 $, four consecutive second array $ A2 $ and the last two third array $ A3 $.

__Tip:__ Use the function _np.split()_.

In [312]:
# enter solution here
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
print(A)
A1,A2,A3 = np.split(A,[2,6],axis=1)
print(A1)
print(A2)
print(A3)

[[0 0 4 2 3 3 1 1]
 [0 0 5 1 0 4 1 1]
 [0 0 6 6 4 1 1 1]
 [0 0 0 6 3 2 1 1]
 [0 0 1 5 0 1 1 1]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[4 2 3 3]
 [5 1 0 4]
 [6 6 4 1]
 [0 6 3 2]
 [1 5 0 1]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


### <a name='5'></a> Exercise 55
The following numpy array $ A $ is given:

```
A = np.random.randint(low=0, high=2, size=(10, 6))
```

Calculate the total number of non-zero elements for this array.

__Tip:__ Use the function _np.count_nonzero()_.


In [318]:
# enter solution here
A = np.random.randint(low=0, high=2, size=(10, 6))
print(A)
np.count_nonzero(A)

[[0 0 0 0 1 1]
 [0 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 0 1 0 1 1]
 [1 0 0 0 0 0]
 [1 1 1 1 0 1]
 [0 0 1 1 0 1]
 [0 1 1 0 1 1]
 [0 1 0 1 1 0]
 [1 0 1 0 1 1]]


35

Calculate the total number of non-zero elements for each row in this array.

__Tip:__ Use the function _np.count_nonzero()_.

In [319]:
# enter solution hereA = np.random.randint(low=0, high=2, size=(10, 6))
print(A)
np.count_nonzero(A,axis=1)

[[0 0 0 0 1 1]
 [0 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 0 1 0 1 1]
 [1 0 0 0 0 0]
 [1 1 1 1 0 1]
 [0 0 1 1 0 1]
 [0 1 1 0 1 1]
 [0 1 0 1 1 0]
 [1 0 1 0 1 1]]


array([2, 4, 5, 4, 1, 5, 3, 4, 3, 4], dtype=int64)

### <a name='6'></a> Exercise 56
An example numpy array $ A $ is given below:

```
A = np.random.randn(10, 4)
```

```
array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])
```

Set the numpy library option to print arrays with specified precision. Set its value to 4 and print the $ A $ array.

In [362]:
# enter solution here
# A = np.random.randn(10, 4)
A = np.array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])
# print(A)
# print("****"*10)
np.set_printoptions(precision=4)
A

array([[-0.5344, -1.4951, -0.7893,  0.7437],
       [-0.2122, -0.4269,  0.5014,  1.1582],
       [ 0.2571,  0.3145,  1.3719,  0.1756],
       [-0.3093,  0.6731, -0.2566, -0.3678],
       [ 1.2737, -0.292 , -2.6552,  0.3455],
       [-0.3955, -0.2891,  0.4529, -0.1661],
       [ 0.2149, -2.0223, -0.9431,  1.404 ],
       [-0.0186, -1.6735, -1.0725, -0.9926],
       [ 0.1023, -0.4326, -0.6592,  0.0039],
       [ 0.4778, -0.259 , -0.5747, -0.4215]])

### <a name='7'></a> Exercise 57

The following numpy array $ A $ is given:

```
A = np.array([1.2e-6, 1.7e-7])
```
Set the precision value to 8. Then set the appropriate numpy library option to suppress mathematical notation. Print the array $ A $.

__Expected result:__
```
array([0.0000012 , 0.00000017])
```


In [368]:
# enter solution here
A = np.array([1.2e-6, 1.7e-7])
print(A)
np.set_printoptions(precision=8,suppress=True)
print(A)

[1.2e-06 1.7e-07]
[0.0000012  0.00000017]


### <a name='8'></a> Exercise 58
The following numpy array $ A $ is given:
```
A = np.random.randn(8, 4)
```
Remove the third column from the $ A $ array.

__Expected result:__
```
array([[-0.55692881, -0.66003196,  0.70856031],
       [ 0.22378737, -0.19796576, -0.16889332],
       [ 0.26062786,  0.29865445, -0.92259267],
       [-2.40317659,  1.79961876, -1.96495796],
       [ 0.13051561, -1.7085185 ,  0.54885043],
       [ 1.77268727,  0.38751181, -0.05141955],
       [-1.80858596, -0.45075211,  0.15332866],
       [ 1.94218961, -1.93679529, -1.83350954]])
```
__Tip:__ Use the _np.delete()_ function.


In [379]:
# enter solution here
A = np.random.randn(8, 4)
print(A)
print("********"*10)
# help(np.delete)
np.delete(A,2,axis=1)

[[ 0.10116799  2.51508487  1.07366965 -0.0255285 ]
 [-0.68968395  1.57633069 -0.67782089 -0.68476991]
 [-0.23181255 -0.07732224  0.29663783 -0.23810947]
 [-1.42678671  0.68950645 -1.77497104 -0.59936886]
 [ 0.72213243 -0.08508606  0.62400612 -1.38767672]
 [ 1.22265663 -0.03816151 -1.19215728 -0.86829476]
 [ 0.92324719  1.68267992  1.88152205 -0.5360108 ]
 [ 1.62432994 -1.86182638  0.74717197 -0.57030738]]
********************************************************************************


array([[ 0.10116799,  2.51508487, -0.0255285 ],
       [-0.68968395,  1.57633069, -0.68476991],
       [-0.23181255, -0.07732224, -0.23810947],
       [-1.42678671,  0.68950645, -0.59936886],
       [ 0.72213243, -0.08508606, -1.38767672],
       [ 1.22265663, -0.03816151, -0.86829476],
       [ 0.92324719,  1.68267992, -0.5360108 ],
       [ 1.62432994, -1.86182638, -0.57030738]])

### <a name='9'></a> Exercise 59

A one-dimensional array $ v $ (vector) is given:

```
v = np.array([3, 4, -2])
```
Calculate the norm of the vetor $ v $.


In [382]:
# enter solution here
v = np.array([3, 4, -2])
np.linalg.norm(v)
# Check - Statistics

5.385164807134504

### <a name='10'></a> Exercise 60
An example $ A $ array is given below:

```
A = np.random.randint(10, size=(100, 30))
```
Set the numpy library option to print 10 edge elements. Print the array $ A $.


In [4]:
# enter solution here
A = np.random.randint(10, size=(100, 30))
print(A)
print("******"*10)
# A[::10]
np.set_printoptions(edgeitems=10)
print(A)

[[6 5 4 ... 7 7 0]
 [0 9 2 ... 6 0 2]
 [4 7 0 ... 2 3 5]
 ...
 [1 0 2 ... 2 0 9]
 [8 0 0 ... 1 2 7]
 [0 5 2 ... 3 2 5]]
************************************************************
[[6 5 4 0 1 4 2 2 7 8 ... 9 5 7 8 0 8 1 7 7 0]
 [0 9 2 2 3 7 2 5 5 2 ... 0 6 3 5 8 4 4 6 0 2]
 [4 7 0 9 0 2 5 2 6 6 ... 1 3 4 6 3 9 7 2 3 5]
 [8 0 0 2 4 2 3 8 4 4 ... 6 4 3 6 5 0 0 4 7 6]
 [8 1 3 4 4 8 4 8 7 8 ... 1 5 4 1 8 1 7 8 8 7]
 [5 2 0 1 5 9 7 8 1 1 ... 2 1 7 2 6 3 1 5 5 2]
 [6 0 6 5 7 0 8 1 8 2 ... 8 2 5 3 4 5 9 9 0 7]
 [9 1 5 9 5 5 3 7 0 9 ... 5 4 2 0 1 8 2 2 5 4]
 [2 5 6 3 5 4 1 4 7 9 ... 0 1 1 8 8 5 1 0 1 8]
 [3 9 7 2 5 3 3 4 1 4 ... 0 1 4 7 7 6 9 5 6 9]
 ...
 [9 4 0 6 9 2 0 8 4 2 ... 6 4 4 0 8 2 7 5 5 8]
 [4 5 8 7 9 4 7 7 3 8 ... 5 5 5 5 4 6 0 6 5 2]
 [1 4 8 0 5 4 1 0 5 1 ... 6 6 0 3 0 5 9 8 0 3]
 [7 2 1 0 9 9 9 2 4 8 ... 5 9 9 4 2 0 1 4 0 5]
 [3 7 5 2 7 0 9 2 5 5 ... 8 8 3 8 7 0 1 4 8 6]
 [2 4 2 1 6 5 3 1 5 0 ... 7 5 9 2 1 5 7 8 4 8]
 [8 9 5 3 2 2 3 3 2 5 ... 8 5 8 5 1 1 9 5 3 6]
 [1 0 2 4 9 1 1

In [389]:
# Given array A
A = np.random.randint(10, size=(5, 5))  # Assuming a 5x5 array for illustration

print("Array:")
print(A)

# Print the first row
print("First row:")
print(A[0, :])

# Print the first column
print("\nFirst column:")
print(A[:, 0])

Array:
[[4 1 4 3 0]
 [3 5 9 7 0]
 [2 3 6 9 2]
 [5 7 5 3 2]
 [7 5 2 8 0]]
First row:
[4 1 4 3 0]

First column:
[4 3 2 5 7]


### <a name='1'></a> Exercise 61
The following two arrays $ A $ and $ B $ are given:

```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
```

Determine an array consisting of arithmetic means $ A $ and $ B $ of the corresponding elements.

__Expected result:__
```
array([[3.5, 3.5, 5.5, 3.5],
       [5.5, 3. , 1.5, 5.5]])
```

In [5]:
# enter solution here
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
(A+B)/2

array([[3.5, 3.5, 5.5, 3.5],
       [5.5, 3. , 1.5, 5.5]])

### <a name='2'></a> Exercise 62
The following two arrays $ A $ and $ B $ are given:
```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
```
Multiply arrays element-by-element (element-wise).

In [6]:
# enter solution here
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
(A*B)

array([[12, 12, 18, 10],
       [30,  9,  2, 30]])

### <a name='3'></a> Exercise 63
The following numpy array $ A $ is given:
```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
```
Determine the root of each element of the array $ A $.

__Tip:__ Use the _np.sqrt()_ function.

In [7]:
# enter solution here
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
np.sqrt(A)

array([[1.73205081, 2.        , 3.        , 1.41421356],
       [2.23606798, 1.73205081, 1.41421356, 2.23606798]])

### <a name='4'></a> Exercise 64
The following arrays $ A $ and $ B $ are given:
```
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')
```
Check the Pythagorean formula for sines and cosines on the $ A $ array and then compare the result with the $ B $ array. Use the _np.allclose()_ function.

__Pythagorean formula for sines and cosines:__ For any angle value $\alpha \in R $:
$$sin^2\alpha + cos^2\alpha = 1$$

In [ ]:
# enter solution here
# Check - Stats

### Reminder
### Matrix mulitplication:
$${A} ={\begin{bmatrix}a_{11}&a_{12}&\cdots &a_{1n}\\a_{21}&a_{22}&\cdots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\cdots &a_{mn}\\\end{bmatrix}}$$
A - $m\ x\ n$ matrix

$$ {B} ={\begin{bmatrix}b_{11}&b_{12}&\cdots &b_{1p}\\b_{21}&b_{22}&\cdots &b_{2p}\\\vdots &\vdots &\ddots &\vdots \\b_{n1}&b_{n2}&\cdots &b_{np}\\\end{bmatrix}}$$
B - $n\ x\ p$ matrix

$$C = AB$$
C - $ m \ x \ p $ matrix  
To be able to multiply two matrices, the number of columns in the left matrix must match the number of rows in the right matrix.

Matrix multiplication is not alternating! $$AB \neq BA$$

### Example 1
$ X = \begin{bmatrix}5&3\\3&9\end{bmatrix}$, $ Y= \begin{bmatrix}1\\-1\end{bmatrix} $   
$ X - $ 2x2 matrix  
$ Y - $ 2x1 matrix  
$$Z = X \cdot Y = \begin{bmatrix}5&3\\3&9\end{bmatrix} \cdot \begin{bmatrix}1\\-1\end{bmatrix} = \begin{bmatrix}2\\-6\end{bmatrix}$$
$ Z - $ 2x1 matrix  

### Example 2
$X = \begin{bmatrix}2&-1&3\\3&1&0\end{bmatrix}$, $Y = \begin{bmatrix}2&1&-1\\0&-1&2\\3&2&0\end{bmatrix}$    
  
$X  -$ 2x3 matrix     
$Y - $ 3x3 matrix  
$$Z = X \cdot Y =  \begin{bmatrix}2&-1&3\\3&1&0\end{bmatrix} \cdot \begin{bmatrix}2&1&-1\\0&-1&2\\3&2&0\end{bmatrix} = \begin{bmatrix}13&9&-4\\6&2&-1\end{bmatrix}$$
$Z - $ 2x3 matrix  

### <a name='5'></a> Exercise 65
Two two-dimensional arrays are provided, numpy $ A $ and $ B $.  
$ A $ - dimension matrix $ (3, 2) $  
$ B $ - dimension matrix $ (2, 3) $  
```
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])
```
Perform matrix multiplication of $ A $ and $ B $ arrays.

__Tip:__ Use the _np.dot()_ function.

In [10]:
# enter solution here
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])
A@B
np.dot(A,B)

array([[  5,   6,  10],
       [-18, -12,  -4],
       [ 20,  15,  10]])

### Reminder

### Determinant of the matrix:

$${\displaystyle A={\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{bmatrix}}}$$
$A$ - _nxn_ matrix

#### Signs:

${\displaystyle |A|=\left|{\begin{array}{c}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{array}}\right|} $  lub  $ {\displaystyle \det A=\det {\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{bmatrix}}}$

#### Example:
${\displaystyle \det A={\begin{vmatrix}a_{11}&a_{12}\\a_{21}&a_{22}\end{vmatrix}}=a_{11}a_{22}-a_{12}a_{21}}$

${\displaystyle \det A={\begin{vmatrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\end{vmatrix}}=a_{11}a_{22}a_{33}+a_{21}a_{32}a_{13}+a_{31}a_{12}a_{23}-a_{21}a_{12}a_{33}-a_{11}a_{32}a_{23}-a_{31}a_{22}a_{13}}$

${\displaystyle \det A={\begin{vmatrix}2&4\\-1&3\end{vmatrix}}=2\cdot3-4\cdot(-1)} = 6 + 4 = 10 $

### <a name='6'></a> Exercise 66
The following array (square matrix) $ A $ is given:

```
A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])
```
Compute the determinant of the $ A $ matrix.

__Tip:__ Use the function _np.linalg.det()_.


In [ ]:
# enter solution here
# Check - stats

### <a name='7'></a> Exercise 67
The following array (square matrix) $ A $ is given:
```
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
```
Calculate eigenvalues and their corresponding eigenvectors of the $ A $ matrix.
__Tip:__ Use the function _np.linalg.eig()_.

In [ ]:
# enter solution here
# Check - stats

### Reminder
### Inverse matrix:

$ A $ - square matrix of degree $ n $. The $ A $ matrix has an inverse matrix when there is a $ B $ matrix such as
$$ AB = BA = I $$

$A = \begin{bmatrix}2&4\\-1&3\end{bmatrix}$

### <a name='8'></a> Exercise 68
The following array (square matrix) $ A $ is given:
```
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
```
Find the inverse matrix to the $ A $ matrix.

__Tip:__ Use the function _np.linalg.inv()_.

In [ ]:
# enter solution here

### Reminder

### Matrix trace:

$${\displaystyle A={\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{bmatrix}}}$$
$A$ - nxn matrix

${\displaystyle \operatorname {tr} (A)=\sum _{i=1}^{n}a_{ii}=a_{11}+a_{22}+\dots +a_{nn}}$


#### Example:
$A = \begin{bmatrix}2&4\\-1&3\end{bmatrix}$

${\displaystyle \operatorname {tr} (A)=\sum _{i=1}^{2}a_{ii}=a_{11}+a_{22} = 2 + 3 = 5}$

### <a name='9'></a> Exercise 69
The following array (square matrix) $ A $ is given:
```
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
```
Find the trace of the square matrix $ A $ (sum of elements on the main diagonal).

__Tip:__ Use the _np.trace()_ function.

In [ ]:
# enter solution here

### Reminder
### Transposed matrix:

Replace rows with columns and columns with rows.

#### Example 1:

$A = \begin{bmatrix}2&4\\-1&3\end{bmatrix}$,
$A^{T} = \begin{bmatrix}2&-1\\4&3\end{bmatrix}$

#### Example 2:
$A = \begin{bmatrix}2&1&-1\\0&-1&2\end{bmatrix}$,
$A^{T} = \begin{bmatrix}2&0\\1&-1\\-1&2\end{bmatrix}$

### Exercise 69 continued
Transpose the $ A $ matrix.

In [ ]:
# enter solution here

### <a name='10'> </a> Exercise 70
Two two-dimensional arrays numpy $ A $ and $ B $ are given:  
$ A $ - matrix of $ (4, 2) $ dimension  
$ B $ - matrix of $ (1, 8) $ dimension

```
A = np.array([[2, 0],
              [4, 2],
              [5, 3],
              [4, 2]])
B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])
```
Transform the $ B $ array so that you can do the matrix multiplication of $ A \cdot B $. Perform this multiplication.

__Expected result:__
```
array([[ 8,  0,  4,  2],
       [18,  0, 12, 22],
       [23,  0, 16, 32],
       [18,  0, 12, 22]])
```

In [ ]:
# enter solution here

### <a name='1'></a> Exercise 71
The following $ A $ array is given:
```
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
```
From the second row of the $ A $ array, randomly shuffle the rows in the array.

__Tip:__ Use the _np.random.shuffle()_ function.


In [ ]:
# enter solution here

### <a name='2'></a> Exercise 72
The following array $ A $ is given:

```
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
```
Return an array of indexes that will sort the array $ A $ in ascending order.

__Expected result:__

```
array([5, 2, 1, 0, 4, 3])
```
__Tip:__ Use the _np.argsort()_ function.


In [ ]:
# enter solution here

### <a name='3'></a> Exercise 73

The following array $ A $ is given:
```
A = np.random.randn(10, 8)
```
Round the values of this array to three decimal places.

__Tip:__ Use the function _np.round()_.


In [ ]:
# enter solution here

### <a name='4'></a> Exercise 74
Determine the roots of the polynomial:
* $W(x) = 4x^2 + 5x + 1$

Check the solution.

__Tip:__ Use the _np.roots()_ and _np.polyval()_ functions.

In [ ]:
# enter solution here

### <a name='5'></a> Exercise 75
Determine the roots of polynomials:
* $Q(x) = 2x^3 + 4x^2 -5x + 1$
* $R(x) = 2x^3 -5x + 1$

__Tip:__ Use the _np.roots()_ function.


In [ ]:
# enter solution here

### <a name='6'></a> Exercise 76
Polynomials are given:
* $W(x) = 4x^2 + 5x + 1$
* $Q(x) = 2x^3 + 4x^2 -5x + 1$


In [ ]:
# enter solution here

Perform:
* $ W (x) + Q (x) $

In [ ]:
# enter solution here

* $W(x) - Q(x)$


In [ ]:
# enter solution here

* $W(x) * Q(x)$


In [ ]:
# enter solution here

* $W(x) + 2Q(x)$

In [ ]:
# enter solution here

### <a name='7'></a> Exercise 77
The array below is given:

```
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
```
Use the sign function for the array $ A $. As a reminder, the function works as follows: returns -1 for negative values, zero for zero, and 1 for positive values.

__Expected result:__

```
array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])
```
__Tip:__ Use the _np.sign()_ function.

In [ ]:
# enter solution here

### <a name='8'></a> Exercise 78
Using the _np.arange()_ function, generate the following array:

```
array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')
```


In [13]:
# enter solution here
np.arange('2021-01-01','2021-02-01',dtype='datetime64[D]')

array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')

### <a name='9'></a> Exercise 79

Using the _np.arange()_ function, generate the following array:

```
array([['2021-01', '2021-02', '2021-03'],
       ['2021-04', '2021-05', '2021-06'],
       ['2021-07', '2021-08', '2021-09'],
       ['2021-10', '2021-11', '2021-12']], dtype='datetime64[M]')
```


In [17]:
# enter solution here
np.arange('2021-01','2022-01',dtype='datetime64[M]').reshape(4,3)

array([['2021-01', '2021-02', '2021-03'],
       ['2021-04', '2021-05', '2021-06'],
       ['2021-07', '2021-08', '2021-09'],
       ['2021-10', '2021-11', '2021-12']], dtype='datetime64[M]')

### <a name='10'></a> Exercise 80
Using the _np.datetime64()_ function, generate today's date (the date you were doing the exercise).

In [19]:
# enter solution here
np.datetime64('today')

numpy.datetime64('2023-10-29')

### <a name='1'></a> Exercise 81
Generate all dates for mondays from January and February 2020 as a numpy array.

__Expected result:__
```
array(['2020-01-06', '2020-01-13', '2020-01-20', '2020-01-27', '2020-02-03', '2020-02-10',
       '2020-02-17', '2020-02-24'], dtype='datetime64[D]')
```

In [23]:
# enter solution here
np.arange('2020-01-06','2020-03-01',7,dtype='datetime64')

array(['2020-01-06', '2020-01-13', '2020-01-20', '2020-01-27',
       '2020-02-03', '2020-02-10', '2020-02-17', '2020-02-24'],
      dtype='datetime64[D]')

### <a name='2'></a> Exercise 82
Two $ A $ and $ B $ arrays are given:
```
A = np.array(['001', '002', '003'], dtype=np.str)
B = np.array(['XC', 'YC', 'ZC'], dtype=np.str)
```
Merge them together as shown below:

```
array(['001XC', '002YC', '003ZC'], dtype='<U5')
```

__Tip:__ Use the function _np.char.add()_.

In [27]:
# enter solution here
A = np.array(['001', '002', '003'], dtype=np.str)
B = np.array(['XC', 'YC', 'ZC'], dtype=np.str)
# help(np.char.add)
np.char.add(A,B)

C:\Users\theve\AppData\Local\Temp\ipykernel_4756\3168287411.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  A = np.array(['001', '002', '003'], dtype=np.str)
C:\Users\theve\AppData\Local\Temp\ipykernel_4756\3168287411.py:3: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  B = np.array(['XC', 'YC', 'ZC'], dtype=np.str)


array(['001XC', '002YC', '003ZC'], dtype='<U5')

### <a name='3'></a> Exercise 83
The array below is given:

```
A = np.array(['1', '2', '3'], dtype=np.str)
```
Add '000' (3 zeros) to the beginning of each element of the array.

__Tip:__ Use the function _np.char.add()_ or _np.char.rjust()_ or _np.char.zfill()_.


In [39]:
# enter solution here
A = np.array(['1', '2', '3'], dtype=np.str)
np.char.add('000',A)
np.char.rjust(A,width=4,fillchar='0')
np.char.zfill(A,width=4)
# help(np.char.zfill)

C:\Users\theve\AppData\Local\Temp\ipykernel_4756\2263843471.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  A = np.array(['1', '2', '3'], dtype=np.str)


array(['0001', '0002', '0003'], dtype='<U4')

### <a name='4'></a> Exercise 84
The array below is given:
```
A = np.array([['PLW CDR 11B TEN', 'AMC LPP'],
              ['CDR PKO KGH', 'CCC QMK']], dtype=np.str)
```
Split each element of the above array by spaces, obtaining a list of values in each place.

__Expected result:__
```
array([[list(['PLW', 'CDR', '11B', 'TEN']), list(['AMC', 'LPP'])],
       [list(['CDR', 'PKO', 'KGH']), list(['CCC', 'QMK'])]], dtype=object)
```
__Tip:__ Use the function _np.char.split()_.


In [41]:
# enter solution here
A = np.array([['PLW CDR 11B TEN', 'AMC LPP'],
              ['CDR PKO KGH', 'CCC QMK']], dtype=np.str)
# help(np.char.split)
np.char.split(A,sep=' ')

C:\Users\theve\AppData\Local\Temp\ipykernel_4756\3282864504.py:3: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ['CDR PKO KGH', 'CCC QMK']], dtype=np.str)


array([[list(['PLW', 'CDR', '11B', 'TEN']), list(['AMC', 'LPP'])],
       [list(['CDR', 'PKO', 'KGH']), list(['CCC', 'QMK'])]], dtype=object)

### <a name='5'></a> Exercise 85
The array below is given:
```
A = np.array([['#summer#time#mood'],
              ['#sport#time']])
```
Replace all # with spaces and then remove any unnecessary spaces around the text.

__Expected result:__
```
array([['summer time mood'],
       ['sport time']], dtype='<U17')
```


In [45]:
# enter solution here
A = np.array([['#summer#time#mood'],
              ['#sport#time']])
np.char.strip(np.char.replace(A,"#"," "))

array([['summer time mood'],
       ['sport time']], dtype='<U17')

### <a name='6'></a> Exercise 86
The following array is provided:

```
A = np.array([['#summer#time#mood', '#vibe'],
              ['#sport#time', '#good#time'],
              ['#event#summer', '#fast#move']])
```
Count the number of occurrences of the word 'time' in each element of the $ A $ array.

__Tip:__ Use the _np.char.count()_ function.



In [47]:
# enter solution here
A = np.array([['#summer#time#mood', '#vibe'],
              ['#sport#time', '#good#time'],
              ['#event#summer', '#fast#move']])
# help(np.char.count)
np.char.count(A,"time")

array([[1, 0],
       [1, 1],
       [0, 0]])

### <a name='7'></a> Exercise 87
The following text is provided containing data (companies from the WIG20 index):

```
text = """ALIOR	PLALIOR00045	88 860 000	1 386 216 000	0,891	2,16	14
CCC	PLCCC0000016	27 918 000	1 292 603 400	0,831	5,28	42
CDPROJEKT	PLOPTTC00011	67 348 000	22 864 646 000	14,702	7,39	7
CYFRPLSAT	PLCFRPT00013	275 301 000	6 854 994 900	4,408	1,17	14
DINOPL	PLDINPL00011	47 937 000	8 916 282 000	5,733	9,13	12
JSW	PLJSW0000015	52 636 000	716 902 320	0,461	1,51	24
KGHM	PLKGHM000017	136 410 000	9 881 540 400	6,354	4,78	8
LOTOS	PLLOTOS00025	86 543 000	5 609 717 260	3,607	2,91	16
LPP	PLLPP0000011	1 306 000	7 444 200 000	4,787	1,43	19
MBANK	PLBRE0000012	12 997 000	2 830 746 600	1,820	0,42	24
ORANGEPL	PLTLKPL00017	647 357 000	4 285 503 340	2,756	1,16	13
PEKAO	PLPEKAO00016	176 379 000	9 619 710 660	6,185	5,27	9
PGE	PLPGER000010	796 776 000	3 561 588 720	2,290	2,88	18
PGNIG	PLPGNIG00014	1 624 608 000	6 072 784 704	3,905	1,56	12
PKNORLEN	PLPKN0000018	289 049 000	17 701 360 760	11,382	12,44	8
PKOBP	PLPKO0000016	857 593 000	18 807 014 490	12,093	10,49	9
PLAY	LU1642887738	114 151 000	3 696 209 380	2,377	1,47	16
PZU	PLPZU0000011	568 305 000	17 515 160 100	11,262	6,64	6
SANPL	PLBZ00000044	33 207 000	5 213 499 000	3,352	1,91	18
TAURONPE	PLTAURN00011	1 043 590 000	1 252 308 000	0,805	1,21	33"""
```

__Columns mean \:__

Instrument | ISIN code | Package | Package (PLN) | Share in portfolio (%) | Share in trading shares and PDAs per session (%) | Average spread per session

Split text into lines. Then divide each line by the tab character `\t` and build a numpy array (without headers) containing the following data. Assign the resulting array to the _result_ variable.

__Expected result:__
```
array([['ALIOR', 'PLALIOR00045', '88 860 000', '1 386 216 000', '0,891', '2,16', '14'],
       ['CCC', 'PLCCC0000016', '27 918 000', '1 292 603 400', '0,831', '5,28', '42'],
       ['CDPROJEKT', 'PLOPTTC00011', '67 348 000', '22 864 646 000', '14,702', '7,39', '7'],
       ['CYFRPLSAT', 'PLCFRPT00013', '275 301 000', '6 854 994 900', '4,408', '1,17', '14'],
       ['DINOPL', 'PLDINPL00011', '47 937 000', '8 916 282 000', '5,733', '9,13', '12'],
       ['JSW', 'PLJSW0000015', '52 636 000', '716 902 320', '0,461', '1,51', '24'],
       ['KGHM', 'PLKGHM000017', '136 410 000', '9 881 540 400', '6,354', '4,78', '8'],
       ['LOTOS', 'PLLOTOS00025', '86 543 000', '5 609 717 260', '3,607', '2,91', '16'],
       ['LPP', 'PLLPP0000011', '1 306 000', '7 444 200 000', '4,787', '1,43', '19'],
       ['MBANK', 'PLBRE0000012', '12 997 000', '2 830 746 600', '1,820', '0,42', '24'],
       ['ORANGEPL', 'PLTLKPL00017', '647 357 000', '4 285 503 340', '2,756', '1,16', '13'],
       ['PEKAO', 'PLPEKAO00016', '176 379 000', '9 619 710 660', '6,185', '5,27', '9'],
       ['PGE', 'PLPGER000010', '796 776 000', '3 561 588 720', '2,290', '2,88', '18'],
       ['PGNIG', 'PLPGNIG00014', '1 624 608 000', '6 072 784 704', '3,905', '1,56', '12'],
       ['PKNORLEN', 'PLPKN0000018', '289 049 000', '17 701 360 760', '11,382', '12,44', '8'],
       ['PKOBP', 'PLPKO0000016', '857 593 000', '18 807 014 490', '12,093', '10,49', '9'],
       ['PLAY', 'LU1642887738', '114 151 000', '3 696 209 380', '2,377', '1,47', '16'],
       ['PZU', 'PLPZU0000011', '568 305 000', '17 515 160 100', '11,262', '6,64', '6'],
       ['SANPL', 'PLBZ00000044', '33 207 000', '5 213 499 000', '3,352', '1,91', '18'],
       ['TAURONPE', 'PLTAURN00011', '1 043 590 000', '1 252 308 000', '0,805', '1,21', '33']],
      dtype='<U14')
```


In [62]:
text = """ALIOR	PLALIOR00045	88 860 000	1 386 216 000	0,891	2,16	14
CCC	PLCCC0000016	27 918 000	1 292 603 400	0,831	5,28	42
CDPROJEKT	PLOPTTC00011	67 348 000	22 864 646 000	14,702	7,39	7
CYFRPLSAT	PLCFRPT00013	275 301 000	6 854 994 900	4,408	1,17	14
DINOPL	PLDINPL00011	47 937 000	8 916 282 000	5,733	9,13	12
JSW	PLJSW0000015	52 636 000	716 902 320	0,461	1,51	24
KGHM	PLKGHM000017	136 410 000	9 881 540 400	6,354	4,78	8
LOTOS	PLLOTOS00025	86 543 000	5 609 717 260	3,607	2,91	16
LPP	PLLPP0000011	1 306 000	7 444 200 000	4,787	1,43	19
MBANK	PLBRE0000012	12 997 000	2 830 746 600	1,820	0,42	24
ORANGEPL	PLTLKPL00017	647 357 000	4 285 503 340	2,756	1,16	13
PEKAO	PLPEKAO00016	176 379 000	9 619 710 660	6,185	5,27	9
PGE	PLPGER000010	796 776 000	3 561 588 720	2,290	2,88	18
PGNIG	PLPGNIG00014	1 624 608 000	6 072 784 704	3,905	1,56	12
PKNORLEN	PLPKN0000018	289 049 000	17 701 360 760	11,382	12,44	8
PKOBP	PLPKO0000016	857 593 000	18 807 014 490	12,093	10,49	9
PLAY	LU1642887738	114 151 000	3 696 209 380	2,377	1,47	16
PZU	PLPZU0000011	568 305 000	17 515 160 100	11,262	6,64	6
SANPL	PLBZ00000044	33 207 000	5 213 499 000	3,352	1,91	18
TAURONPE	PLTAURN00011	1 043 590 000	1 252 308 000	0,805	1,21	33"""

# enter solution here
lines = text.split("\n")
lines
result = np.array([line.split('\t') for line in lines])
result
# for line in lines:
#     line.split("\t")
#     print(line)
# result.shape

array([['ALIOR', 'PLALIOR00045', '88 860 000', '1 386 216 000', '0,891',
        '2,16', '14'],
       ['CCC', 'PLCCC0000016', '27 918 000', '1 292 603 400', '0,831',
        '5,28', '42'],
       ['CDPROJEKT', 'PLOPTTC00011', '67 348 000', '22 864 646 000',
        '14,702', '7,39', '7'],
       ['CYFRPLSAT', 'PLCFRPT00013', '275 301 000', '6 854 994 900',
        '4,408', '1,17', '14'],
       ['DINOPL', 'PLDINPL00011', '47 937 000', '8 916 282 000', '5,733',
        '9,13', '12'],
       ['JSW', 'PLJSW0000015', '52 636 000', '716 902 320', '0,461',
        '1,51', '24'],
       ['KGHM', 'PLKGHM000017', '136 410 000', '9 881 540 400', '6,354',
        '4,78', '8'],
       ['LOTOS', 'PLLOTOS00025', '86 543 000', '5 609 717 260', '3,607',
        '2,91', '16'],
       ['LPP', 'PLLPP0000011', '1 306 000', '7 444 200 000', '4,787',
        '1,43', '19'],
       ['MBANK', 'PLBRE0000012', '12 997 000', '2 830 746 600', '1,820',
        '0,42', '24'],
       ['ORANGEPL', 'PLTLKPL00017', '64

### <a name='8'></a> Exercise 88
From the _result_ array from the previous exercise, remove all spaces in the text and replace all commas with periods.

In [71]:
# enter solution here
result_clean = np.char.replace(np.char.replace(result," ",""),",",".")
result_clean

array([['ALIOR', 'PLALIOR00045', '88860000', '1386216000', '0.891',
        '2.16', '14'],
       ['CCC', 'PLCCC0000016', '27918000', '1292603400', '0.831', '5.28',
        '42'],
       ['CDPROJEKT', 'PLOPTTC00011', '67348000', '22864646000', '14.702',
        '7.39', '7'],
       ['CYFRPLSAT', 'PLCFRPT00013', '275301000', '6854994900', '4.408',
        '1.17', '14'],
       ['DINOPL', 'PLDINPL00011', '47937000', '8916282000', '5.733',
        '9.13', '12'],
       ['JSW', 'PLJSW0000015', '52636000', '716902320', '0.461', '1.51',
        '24'],
       ['KGHM', 'PLKGHM000017', '136410000', '9881540400', '6.354',
        '4.78', '8'],
       ['LOTOS', 'PLLOTOS00025', '86543000', '5609717260', '3.607',
        '2.91', '16'],
       ['LPP', 'PLLPP0000011', '1306000', '7444200000', '4.787', '1.43',
        '19'],
       ['MBANK', 'PLBRE0000012', '12997000', '2830746600', '1.820',
        '0.42', '24'],
       ['ORANGEPL', 'PLTLKPL00017', '647357000', '4285503340', '2.756',
        '1.16', 

Then extract column 'Share in portfolio (%)' convert its type to _float_ and calculate the sum for this column. Check if it's 100%.

In [109]:
# enter solution here
# np.sum(result_clean[:,4].astype(float))
# help(np.isclose)
# extract the share column
share = result_clean[:,4]
# convert to float
share_float = share.astype(float)
# sum of the share
share_sum = np.sum(share_float)
# check if its close to 100%
np.isclose(share_sum,100)

[ 0.891  0.831 14.702  4.408  5.733  0.461  6.354  3.607  4.787  1.82
  2.756  6.185  2.29   3.905 11.382 12.093  2.377 11.262  3.352  0.805]


True

### <a name='9'></a> Exercise 89
From the _result_ array, extract all the rows with the company name beginning with the letter P and assign it to the variable _stocks_startswith_P_.

__Expected result:__

```
array([['PEKAO', 'PLPEKAO00016', '176379000', '9619710660', '6.185', '5.27', '9'],
       ['PGE', 'PLPGER000010', '796776000', '3561588720', '2.290', '2.88', '18'],
       ['PGNIG', 'PLPGNIG00014', '1624608000', '6072784704', '3.905', '1.56', '12'],
       ['PKNORLEN', 'PLPKN0000018', '289049000', '17701360760', '11.382', '12.44', '8'],
       ['PKOBP', 'PLPKO0000016', '857593000', '18807014490', '12.093', '10.49', '9'],
       ['PLAY', 'LU1642887738', '114151000', '3696209380', '2.377', '1.47', '16'],
       ['PZU', 'PLPZU0000011', '568305000', '17515160100', '11.262', '6.64', '6']], dtype='<U12')
```

In [106]:
# enter solution here
stocks_startswith_P = result_clean[np.char.startswith(result[:,0],'P')]
stocks_startswith_P

array([['PEKAO', 'PLPEKAO00016', '176379000', '9619710660', '6.185',
        '5.27', '9'],
       ['PGE', 'PLPGER000010', '796776000', '3561588720', '2.290',
        '2.88', '18'],
       ['PGNIG', 'PLPGNIG00014', '1624608000', '6072784704', '3.905',
        '1.56', '12'],
       ['PKNORLEN', 'PLPKN0000018', '289049000', '17701360760', '11.382',
        '12.44', '8'],
       ['PKOBP', 'PLPKO0000016', '857593000', '18807014490', '12.093',
        '10.49', '9'],
       ['PLAY', 'LU1642887738', '114151000', '3696209380', '2.377',
        '1.47', '16'],
       ['PZU', 'PLPZU0000011', '568305000', '17515160100', '11.262',
        '6.64', '6']], dtype='<U12')

### <a name='10'></a> Exercise 90
Using the variable _stocks_startswith_P_, calculate the total share of companies whose name begins with the letter P. Round the result to two decimal places.

In [114]:
# enter solution here
round(np.sum(stocks_startswith_P[:,4].astype(float)),2)

49.49

### <a name='1'></a> Exercise 91
The following string _wig_games_raw_ is provided containing data on the WIG.GAMES sector index:

```
wig_games_raw = """Profile	Time	Course	Change	Change%	Ref.	Open	Low	High	Volume	Turn	Share
11B (11BIT)	17 kwi 17:01	391.00	+8.00	(+2.09%)	383.00	383.50	383.00	394.00	12 784	4 994 874	19.034%
CDR (CDPROJEKT)	17 kwi 17:01	339.50	+5.30	(+1.59%)	334.20	338.30	337.00	344.20	233 059	79 245 368	39.618%
CIG (CIGAMES)	17 kwi 17:03	0.742	-0.012	(-1.59%)	0.754	0.772	0.730	0.772	1 311 078	971 459	1.855%
PLW (PLAYWAY)	17 kwi 17:03	387.50	+18.00	(+4.87%)	369.50	374.00	373.00	388.00	33 206	12 661 786	10.638%
TEN (TSGAMES)	17 kwi 17:02	349.50	+22.50	(+6.88%)	327.00	332.00	330.00	353.50	39 793	13 697 060	28.855%"""
```
Build a numpy array from this data and name it _wig_games_.

__Expected result:__
```
array([['Profil', 'Czas', 'Kurs', 'Zmiana', 'Zmiana%', 'Odn.', 'Otw.', 'Min.', 'Max.', 'Wolumen', 'Obrót', 'Udział'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '+8.00', '(+2.09%)', '383.00', '383.50', '383.00', '394.00', '12784', '4994874', '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '+5.30', '(+1.59%)', '334.20', '338.30', '337.00', '344.20', '233059', '79245368', '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '-0.012', '(-1.59%)', '0.754', '0.772', '0.730', '0.772', '1311078', '971459', '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '+18.00', '(+4.87%)', '369.50', '374.00', '373.00', '388.00', '33206', '12661786', '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '+22.50', '(+6.88%)', '327.00', '332.00', '330.00', '353.50', '39793', '13697060', '28.855%']], dtype='<U14')
```


In [125]:
wig_games_raw = """Profile	Time	Course	Change	Change%	Ref.	Open	Low	High	Volume	Turn	Share
11B (11BIT)	17 kwi 17:01	391.00	+8.00	(+2.09%)	383.00	383.50	383.00	394.00	12 784	4 994 874	19.034%
CDR (CDPROJEKT)	17 kwi 17:01	339.50	+5.30	(+1.59%)	334.20	338.30	337.00	344.20	233 059	79 245 368	39.618%
CIG (CIGAMES)	17 kwi 17:03	0.742	-0.012	(-1.59%)	0.754	0.772	0.730	0.772	1 311 078	971 459	1.855%
PLW (PLAYWAY)	17 kwi 17:03	387.50	+18.00	(+4.87%)	369.50	374.00	373.00	388.00	33 206	12 661 786	10.638%
TEN (TSGAMES)	17 kwi 17:02	349.50	+22.50	(+6.88%)	327.00	332.00	330.00	353.50	39 793	13 697 060	28.855%"""

# enter solution here
# Detailed
# lists = wig_games_raw.split('\n')
# lists
# arr = np.array([list.split('\t') for list in lists])
# arr
# result_clean = np.char.replace(arr," ","")
# result_clean
wig_games_array = np.char.replace(np.array([list.split('\t') for list in wig_games_raw.split('\n')])," ",'')
wig_games_array

array([['Profile', 'Time', 'Course', 'Change', 'Change%', 'Ref.', 'Open',
        'Low', 'High', 'Volume', 'Turn', 'Share'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '+8.00', '(+2.09%)',
        '383.00', '383.50', '383.00', '394.00', '12784', '4994874',
        '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '+5.30', '(+1.59%)',
        '334.20', '338.30', '337.00', '344.20', '233059', '79245368',
        '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '-0.012', '(-1.59%)',
        '0.754', '0.772', '0.730', '0.772', '1311078', '971459',
        '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '+18.00', '(+4.87%)',
        '369.50', '374.00', '373.00', '388.00', '33206', '12661786',
        '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '+22.50', '(+6.88%)',
        '327.00', '332.00', '330.00', '353.50', '39793', '13697060',
        '28.855%']], dtype='<U14')

### <a name='2'></a> Exercise 92
Remove the columns from the _wig_games_ array from the previous exercise:
* Change
* Change%
* Ref.
* Volume

__Expected result:__
```
array([['Profile', 'Time', 'Course', 'Open', 'Low', 'High', 'Turn', 'Share'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '383.50', '383.00', '394.00', '4994874', '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '338.30', '337.00', '344.20', '79245368', '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '0.772', '0.730', '0.772', '971459', '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '374.00', '373.00', '388.00', '12661786', '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '332.00', '330.00', '353.50', '13697060', '28.855%']], dtype='<U14')
```


In [128]:
# enter solution here
wig_games_array[0]
# 3,4,5,9,
wig_games = np.delete(wig_games_array,[3,4,5,9],1)
wig_games

array([['Profile', 'Time', 'Course', 'Open', 'Low', 'High', 'Turn',
        'Share'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '383.50', '383.00',
        '394.00', '4994874', '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '338.30', '337.00',
        '344.20', '79245368', '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '0.772', '0.730', '0.772',
        '971459', '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '374.00', '373.00',
        '388.00', '12661786', '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '332.00', '330.00',
        '353.50', '13697060', '28.855%']], dtype='<U14')

### <a name='3'></a> Exercise 93
Save the array _wig_games_ from the previous exercise to the _wig_games.csv_ file.

In [131]:
# enter solution here
np.savetxt("wig_games.csv",wig_games,delimiter=',',fmt='%s')

In [140]:
import pandas as pd
wig_games_df = pd.read_csv('wig_games.csv')
wig_games_df.columns

Index(['Profile', 'Time', 'Course', 'Open', 'Low', 'High', 'Turn', 'Share'], dtype='object')

Run the cell below to check.

In [135]:
# !head wig_games.csv -- this doesnt work as its related to linux
import csv
with open('wig_games.csv','r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

['Profile', 'Time', 'Course', 'Open', 'Low', 'High', 'Turn', 'Share']
['11B(11BIT)', '17kwi17:01', '391.00', '383.50', '383.00', '394.00', '4994874', '19.034%']
['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '338.30', '337.00', '344.20', '79245368', '39.618%']
['CIG(CIGAMES)', '17kwi17:03', '0.742', '0.772', '0.730', '0.772', '971459', '1.855%']
['PLW(PLAYWAY)', '17kwi17:03', '387.50', '374.00', '373.00', '388.00', '12661786', '10.638%']
['TEN(TSGAMES)', '17kwi17:02', '349.50', '332.00', '330.00', '353.50', '13697060', '28.855%']


### <a name='4'></a> Exercise 94
Load the contents of the _wig_games.csv_ file into the _wig_games_new_ variable.

In [141]:
# enter solution here
import pandas as pd
wig_games_new = pd.read_csv('wig_games.csv')
wig_games_new.columns

Index(['Profile', 'Time', 'Course', 'Open', 'Low', 'High', 'Turn', 'Share'], dtype='object')

### <a name='5'></a> Exercise 95
The following string _playway_raw_ is provided containing Playway's March 2020 listings:

```
playway_raw = """Date,Open,High,Low,Close,Volume
2020-03-02,305,324.5,283.5,310,64081
2020-03-03,325.5,340.5,320,340.5,55496
2020-03-04,324,340.5,315,330,36152
2020-03-05,344,344,310,315,35992
2020-03-06,306.5,307,291,305,32539
2020-03-09,274,291,250,258,79402
2020-03-10,278,284.5,256,264,35700
2020-03-11,270,270,238.5,245,60445
2020-03-12,218,228,196,197,94031
2020-03-13,210,229,198.8,211,100412
2020-03-16,205,248,197.8,240.5,50659
2020-03-17,245,269,232.5,264,99480
2020-03-18,264,280,251,270,70136
2020-03-19,267,280,267,279.5,30732
2020-03-20,297.5,307,280,280.5,43426
2020-03-23,274,289,258,285,37098
2020-03-24,305,309,296.5,309,31939
2020-03-25,313,330,295,304,46724
2020-03-26,300,309,295.5,300,27213
2020-03-27,302,306.5,290,296,13466
2020-03-30,299,300,287,300,10316
2020-03-31,302.5,309,302,306.5,15698"""
```

Create an array named _playway_ and assign the following data to it.

In [148]:
playway_raw = """Date,Open,High,Low,Close,Volume
2020-03-02,305,324.5,283.5,310,64081
2020-03-03,325.5,340.5,320,340.5,55496
2020-03-04,324,340.5,315,330,36152
2020-03-05,344,344,310,315,35992
2020-03-06,306.5,307,291,305,32539
2020-03-09,274,291,250,258,79402
2020-03-10,278,284.5,256,264,35700
2020-03-11,270,270,238.5,245,60445
2020-03-12,218,228,196,197,94031
2020-03-13,210,229,198.8,211,100412
2020-03-16,205,248,197.8,240.5,50659
2020-03-17,245,269,232.5,264,99480
2020-03-18,264,280,251,270,70136
2020-03-19,267,280,267,279.5,30732
2020-03-20,297.5,307,280,280.5,43426
2020-03-23,274,289,258,285,37098
2020-03-24,305,309,296.5,309,31939
2020-03-25,313,330,295,304,46724
2020-03-26,300,309,295.5,300,27213
2020-03-27,302,306.5,290,296,13466
2020-03-30,299,300,287,300,10316
2020-03-31,302.5,309,302,306.5,15698"""

# enter solution here
playway=np.array([list.split(",") for list in playway_raw.split("\n")])
playway

array([['Date', 'Open', 'High', 'Low', 'Close', 'Volume'],
       ['2020-03-02', '305', '324.5', '283.5', '310', '64081'],
       ['2020-03-03', '325.5', '340.5', '320', '340.5', '55496'],
       ['2020-03-04', '324', '340.5', '315', '330', '36152'],
       ['2020-03-05', '344', '344', '310', '315', '35992'],
       ['2020-03-06', '306.5', '307', '291', '305', '32539'],
       ['2020-03-09', '274', '291', '250', '258', '79402'],
       ['2020-03-10', '278', '284.5', '256', '264', '35700'],
       ['2020-03-11', '270', '270', '238.5', '245', '60445'],
       ['2020-03-12', '218', '228', '196', '197', '94031'],
       ['2020-03-13', '210', '229', '198.8', '211', '100412'],
       ['2020-03-16', '205', '248', '197.8', '240.5', '50659'],
       ['2020-03-17', '245', '269', '232.5', '264', '99480'],
       ['2020-03-18', '264', '280', '251', '270', '70136'],
       ['2020-03-19', '267', '280', '267', '279.5', '30732'],
       ['2020-03-20', '297.5', '307', '280', '280.5', '43426'],
       [

Delete the column named 'Date'. Assign only column values without headers to the _playway_values_ variable. Convert the array to the _float_ data type.

__Expected result:__
```
array([[   305. ,    324.5,    283.5,    310. ,  64081. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ],
       [   313. ,    330. ,    295. ,    304. ,  46724. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ],
       [   302. ,    306.5,    290. ,    296. ,  13466. ],
       [   299. ,    300. ,    287. ,    300. ,  10316. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ]])
```

In [221]:
# enter solution here
remove_date = np.delete(playway,0,axis=1)
# playway_values = np.delete(remove_date,0,axis=0).astype(float)
playway_values = remove_date[1:].astype(float)
playway_values

array([[   305. ,    324.5,    283.5,    310. ,  64081. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. 

### <a name='6'></a> Exercise 96
For the _playway_values_ array from the previous exercise, calculate the average value for each column. Round the result to two decimal places.

In [166]:
# enter solution here
print(np.round(np.mean(playway_values,axis=0),2))
print(np.round(np.average(playway_values,axis=0),2))

[  283.14   295.25   268.69   282.3  48688.05]
[  283.14   295.25   268.69   282.3  48688.05]


For the _playway_values_ array from the previous exercise, calculate the minimum value for each column. Round the result to two decimal places.

In [168]:
# enter solution here
print(np.round(np.min(playway_values,axis=0),2))

[  205.   228.   196.   197. 10316.]


For the _playway_values_ array from the previous exercise, calculate the maximum value for each column. Round the result to two decimal places.

In [169]:
# enter solution here
print(np.round(np.max(playway_values,axis=0),2))

[   344.     344.     320.     340.5 100412. ]


Calculate the difference between the maximum and minimum value for each column.

In [173]:
# enter solution here
# help(np.ptp)
print(np.ptp(playway_values,axis=0))

[  139.    116.    124.    143.5 90096. ]


### <a name='7'></a> Exercise 97
Using the _playway_values_ array, calculate the new column: the difference between the highest and lowest price.

Steps:
1. assign the calculated difference to the _max_min_diff_ variable
2. add the calculated column (variable _max_min_diff_) to the array _playway_values_ at the end.

__Expected result:__
```
array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5],
       [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5],
       [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ]])
```

In [319]:
# enter solution here
playway_values_t = playway_values[:4,:]
playway_values_t
max_min_diff = np.ptp(playway_values_t[:,1:3],axis=1)
print(max_min_diff)
# # print(max_min_diff.shape)
max_min_diff = max_min_diff[:,np.newaxis]
# # print(max_min_diff)
# # print(max_min_diff.shape)
# # playway_values = 
# # np.hstack((playway_values_t,max_min_diff))
np.append(playway_values_t,max_min_diff,axis=1)
# # print(playway_values)
# Check --- here we are getting the value in scientific notation

[41.  20.5 25.5 34. ]


array([[3.0500e+02, 3.2450e+02, 2.8350e+02, 3.1000e+02, 6.4081e+04,
        4.1000e+01],
       [3.2550e+02, 3.4050e+02, 3.2000e+02, 3.4050e+02, 5.5496e+04,
        2.0500e+01],
       [3.2400e+02, 3.4050e+02, 3.1500e+02, 3.3000e+02, 3.6152e+04,
        2.5500e+01],
       [3.4400e+02, 3.4400e+02, 3.1000e+02, 3.1500e+02, 3.5992e+04,
        3.4000e+01]])

### <a name='8'></a> Exercise 98
Extract rows from the array _playway_values_ where closing price is grater than 300.00.

In [279]:
# enter solution here
playway_values[playway_values[:,3] > 300]

array([[  305. ,   324.5,   283.5,   310. , 64081. ],
       [  325.5,   340.5,   320. ,   340.5, 55496. ],
       [  324. ,   340.5,   315. ,   330. , 36152. ],
       [  344. ,   344. ,   310. ,   315. , 35992. ],
       [  306.5,   307. ,   291. ,   305. , 32539. ],
       [  305. ,   309. ,   296.5,   309. , 31939. ],
       [  313. ,   330. ,   295. ,   304. , 46724. ],
       [  302.5,   309. ,   302. ,   306.5, 15698. ]])

### <a name='9'></a> Exercise 99
From the array _playway_values_ extract the first 10 rows with the highest volume value sorted in descending order.

In [309]:
# enter solution here
# np.sort(playway_values,axis=0) # This will sort the values in the array individually on row
sorted_indices = np.argsort(playway_values[:,4])[::-1]
playway_values[sorted_indices][0:11]

array([[   210. ,    229. ,    198.8,    211. , 100412. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ],
       [   305. ,    324.5,    283.5,    310. ,  64081. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ],
       [   313. ,    330. ,    295. ,    304. ,  46724. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ]])

In [289]:
playway_values

array([[   305. ,    324.5,    283.5,    310. ,  64081. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. 

### <a name='10'></a> Exercise 100
Add to the _playway_values_ array column that will return 1 in case the closing price is higher than the opening price and 0 opposite.

__Expected result:__
```
array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ,      1. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5,      1. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5,      1. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ,      0. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ,      0. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ,      0. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5,      0. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5,      0. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ,      0. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2,      1. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2,      1. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5,      1. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ,      1. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ,      1. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ,      0. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ,      1. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5,      1. ],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ,      0. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5,      0. ],
       [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5,      0. ],
       [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ,      1. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ,      1. ]])
```

In [318]:
# enter solution here
stack_value = np.where(playway_values[:,3] > playway_values[:,0],1,0)
np.column_stack((playway_values,stack_value))
# np.column_stack((playway_values,(np.where(playway_values[:,3] > playway_values[:,0],1,0))))
# Check

array([[3.05000e+02, 3.24500e+02, 2.83500e+02, 3.10000e+02, 6.40810e+04,
        1.00000e+00],
       [3.25500e+02, 3.40500e+02, 3.20000e+02, 3.40500e+02, 5.54960e+04,
        1.00000e+00],
       [3.24000e+02, 3.40500e+02, 3.15000e+02, 3.30000e+02, 3.61520e+04,
        1.00000e+00],
       [3.44000e+02, 3.44000e+02, 3.10000e+02, 3.15000e+02, 3.59920e+04,
        0.00000e+00],
       [3.06500e+02, 3.07000e+02, 2.91000e+02, 3.05000e+02, 3.25390e+04,
        0.00000e+00],
       [2.74000e+02, 2.91000e+02, 2.50000e+02, 2.58000e+02, 7.94020e+04,
        0.00000e+00],
       [2.78000e+02, 2.84500e+02, 2.56000e+02, 2.64000e+02, 3.57000e+04,
        0.00000e+00],
       [2.70000e+02, 2.70000e+02, 2.38500e+02, 2.45000e+02, 6.04450e+04,
        0.00000e+00],
       [2.18000e+02, 2.28000e+02, 1.96000e+02, 1.97000e+02, 9.40310e+04,
        0.00000e+00],
       [2.10000e+02, 2.29000e+02, 1.98800e+02, 2.11000e+02, 1.00412e+05,
        1.00000e+00],
       [2.05000e+02, 2.48000e+02, 1.97800e+02, 2.4